### ISSUE TITLE
Comentários no início do código

### ISSUE THREAD

**Issue by drbeco** [JorgeEd13/informatica29JingleBell#10]
Sempre é importante colocar um comentário no início do código com autores, copyright, licença, data e descrição do progrrama.

**Comment by gabrielgou** [comment]
Implementado comentário no Commit [fd91f22](https://github.com/JorgeEd13/informatica29JingleBell/commit/fd91f2222b6c9943033ed9c7c12779ca9106d943)  :thumbsup:
