### ISSUE TITLE
Quadrado mágico

### ISSUE THREAD

**Issue by drbeco** [JorgeEd13/informatica29JingleBell#12]
Vocês sabem o que é na matemática um **quadrado mágico**?

E qual a relação que tem com o jogo-da-velha?

![image](https://cloud.githubusercontent.com/assets/5805111/11985064/d6dd5430-a99f-11e5-95be-b929a642fd23.png)

**Comment by drbeco** [comment]
:question:

**Comment by bmhori** [comment]
Osl

**Comment by bmhori** [comment]
Os numeros 2,4,6 e 8 são pares e ficam nas extreidades do quadrado, que se intrrpretado como a velha, seriam as melhores posições para uma jogada e para implrmentar no modo de jogo dificil.
