### ISSUE TITLE
Feliz Natal!

### ISSUE THREAD

**Issue by drbeco** [JorgeEd13/informatica29JingleBell#14]
**Feliz Natal!**

Um excelente dia de Natal para todos!

**Comment by bmhori** [comment]
Igualmente! :smile:

**Comment by JorgeEd13** [comment]
Felicidade a todos!

**Comment by gabrielgou** [comment]
Feliz Natal!!!

**Comment by wesleysilas** [comment]
Feliz natal, grande Ruben! 
Feliz natal meus amigos!!! 2016 de mt conquista e que possamos estar juntos em Discreta!
