### ISSUE TITLE
Função VOID e identação.

### ISSUE THREAD

**Issue by wesleysilas** [JorgeEd13/informatica29JingleBell#22]
Olhando nosso código, percebi que em alguns trechos havia a função declarada: 
int main (), ao invés de int main (void). 
de acordo com as aulas do nosso orientador devemos sim declarar o VOID.
Além do mais, havia uns erros de identação no abrir de chaves.

vamos ajustar nossa última versão. Vou comecar os ajustes aqui.

**Comment by bmhori** [comment]
Resolvido!
