### ISSUE TITLE
adição de colaboradores, AUTHORS e tudo mais...

### ISSUE THREAD

**Issue by wesleysilas** [JorgeEd13/informatica29JingleBell#5]
jorge vai adicionar os colaboradores e a pasta authors...

**Comment by JorgeEd13** [comment]
Todos adicionados

**Comment by wesleysilas** [comment]
cada um adicionando os seus dados... emails e usuario do git la no authors

**Comment by wesleysilas** [comment]
Adicionei tudo sobre os AUTHORS 100% completo! :+1:
